pipeline {
    agent any

    triggers {
        githubPush()
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/amitgupta9977/ShoppingCart.git', branch: 'main'
            }
        }
        stage('Install') {
            steps {
                sh 'npm install' // Install dependencies
            }
        }
        stage('Build') {
            steps {
                sh 'npm run build' // Build the project
            }
        }
        stage('Test') {
            steps {
                sh 'npm test' // Run tests
            }
        }
    }

    post {
        success {
            echo 'Build successful'
        }
        failure {
            echo 'Build failed'
        }
    }
}
